spring.datasource.url=jdbc:mysql://localhost:3306/travelnest
spring.datasource.username=root
spring.datasource.password=Venu@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081